config/routes.rb
AdminPanel::Application.routes.draw do
  resources :sprints

  root to: 'sprints#index'
end

app/models/sprint.rb
# coding: utf-8
class Sprint < ActiveRecord::Base
  attr_accessible :date_begin, :date_end, :fact_points, :hours_count, :name, :points, :status, :unknown_level

  validates :name, presence: true, length: { maximum: 50 }
  validates :points, :unknown_level, :fact_points, :hours_count, numericality: { greater_than_or_equal_to: 0  }
  validates :status, :date_begin, :date_end, presence: true
  
  validate :date_begin_less_then_date_end
  def date_begin_less_then_date_end
  	errors.add(:date_begin, :date_required) if 
  		!date_begin.blank? and !date_end.blank? and date_begin > date_end
  end

  scope :with_hours, where("hours_count > '0' AND status <> 'Планируемый'")  

  after_save -> { SprintStats.update_stats }  
  after_destroy -> { SprintStats.update_stats }

  def self.where_id(id)
    where(id: id).first
  end
end

app/models/sprint_stats.rb
class SprintStats < ActiveRecord::Base
  attr_accessible :velocity, :points

  validates :velocity, :points, numericality: { greater_then_or_equal_to: 0 }
  
  def self.update_stats
    fact_points = 0
    hours = 0
    velocity = 0
    probable_points = 0
    
    stat = SprintStats.get_first
    sprints_with_hours = Sprint.with_hours
    sprints_with_hours.each do |swh|
      fact_points += swh.fact_points
      hours += swh.hours_count      
    end
    
    if hours > 0
      velocity = (fact_points / hours).round(2)
    end
    stat.velocity = velocity
    if sprints_with_hours.count > 0
      probable_points = (velocity * hours / sprints_with_hours.count).round(2)
    end    
    stat.points = probable_points
    stat.save
  end

  
  def self.get_first
    if SprintStats.count == 0
      SprintStats.create(velocity: 0, points: 0)
    else
      SprintStats.first
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/sprints_controller.rb
# coding: utf-8
class SprintsController < ApplicationController
  def new
    @sprint = Sprint.new
  end

  def show
    @sprint = SprintDecorator.decorate(Sprint.where_id(params[:id]))
  end

  def create
    @sprint = Sprint.new(params[:sprint])
    if @sprint.save
      flash[:success] = "Новый спринт успешно сохранен!"
      redirect_to @sprint
    else
      render 'new'      
    end
  end

  def index    
    @sprints = SprintDecorator.decorate_collection(Sprint.all)
    
    stats = SprintStats.get_first
    @velocity = stats.velocity
    @probable_points = stats.points
  end

  def edit
    @sprint = SprintDecorator.decorate(Sprint.where_id(params[:id]))
  end

  def update
    @sprint = SprintDecorator.decorate(Sprint.where_id(params[:id]))
    if @sprint.update_attributes(params[:sprint])
      flash[:success] = 'Изменения сохранены'
      redirect_to root_path
    else
      render 'edit'
    end   
  end

  def destroy
    SprintDecorator.decorate(Sprint.where_id(params[:id])).destroy
    flash[:success] = 'Спринт успешно удален'
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sprints_helper.rb
module SprintsHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title Sprint panel
    = stylesheet_link_tag "application", media: "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    /[if lt IE 9] script src="http://html5shim.googlecode.com/svn/trunk/html5.js"
  body
    header class="navbar navbar-fixed-top navbar-inverse"
      div class="navbar-inner"
        div class="container"
          a class="brand" href=root_path Спринты
          nav
            ul class="nav pull-right nav-pills"
              li
                = link_to "Создать спринт", new_sprint_path
    div class="container"
      - flash.each do |key, value|
        = content_tag(:div, value, class: "alert alert-#{key}")
      = yield

app/views/shared/_error_messages.html.slim
- if @sprint.errors.any?
  div id="error_explanation"
    div class="alert alert-error" 
      | Форма содержит ошибки
    ul
      - @sprint.errors.full_messages.each do |msg|
        li #{msg} 

app/views/sprints/edit.html.slim
h1 Редактирование спринта
 
div class="row"
 div class="span6 offset3"
  = form_for(@sprint) do |f|
   = render "shared/error_messages"

   = f.label :name, "Наименование"
   = f.text_field :name

   = f.label :date_begin, "Дата начала"
   = f.text_field :date_begin, value: @sprint.begin_date, "data-behaviour" => "datepicker"

   = f.label :date_end, "Дата окончания"
   = f.text_field :date_end, value: @sprint.end_date, "data-behaviour" => "datepicker"

   = f.label :points, "Сложность"
   = f.text_field :points

   = f.label :unknown_level, "Непонятные задания"
   = f.text_field :unknown_level

   = f.label :fact_points, "Итоговая реализация"
   = f.text_field :fact_points

   = f.label :hours_count, "Количество чел/ч"
   = f.text_field :hours_count

   = f.label :status, "Статус"
   = f.select :status, options_for_select(["Планируемый", "Идет", "Успешно", "Провалено"], @sprint.status)

   = f.submit "Применить", class: "btn btn-primary"

app/views/sprints/index.html.slim
h1 Список спринтов

div
  table class="table table-bordered"
    thead
      tr      
        th Наименование
        th Продолжительность
        th Итоговая реализация
        th Количество чел/ч
        th Статус      
    tbody
      - @sprints.each do |one_sprint|                  
        tr class=one_sprint.status_class
          td = one_sprint.show_link
          td #{one_sprint.duration}
          td #{one_sprint.fact_points}
          td #{one_sprint.hours_count}
          td #{one_sprint.status}          

h1 Статистика
div class="span6 offset3"
  p Средняя скорость: #{@velocity}
  p Предполагаемое кол-во поинтов: #{@probable_points}

app/views/sprints/new.html.slim
h1 Создание нового спринта
 
div class="row"
 div class="span6 offset3"
  = form_for(@sprint) do |f|
   = render "shared/error_messages"

   = f.label :name, "Наименование"
   = f.text_field :name

   = f.label :date_begin, "Дата начала"
   = f.text_field :date_begin, value: Date.today(), "data-behaviour" => "datepicker"

   = f.label :date_end, "Дата окончания"
   = f.text_field :date_end, value: Date.today() + 14.day, "data-behaviour" => "datepicker"

   = f.label :points, "Сложность"
   = f.text_field :points

   = f.label :unknown_level, "Непонятные задания"
   = f.text_field :unknown_level

   = f.label :fact_points, "Итоговая реализация"
   = f.text_field :fact_points

   = f.label :hours_count, "Количество чел/ч"
   = f.text_field :hours_count

   = f.label :status, "Статус"
   = f.select :status, options_for_select(["Планируемый", "Идет", "Успешно", "Провалено"])
   
   = f.submit "Добавить спринт", class: "btn btn-primary"

app/views/sprints/show.html.slim
h1 = @sprint.name
 
div class="row"
 div class="span6 offset3"
  div class="well"
    b Продолжительность:
    #{@sprint.duration}
    b Сложность:
    #{@sprint.points.to_int}
    b Кол-во непонятных вопросов:
    #{@sprint.unknown_level.to_int}
    b Итоговая реализация:
    #{@sprint.fact_points}
    b Статус:
    #{@sprint.status}
    b Количество чел/ч:
    #{@sprint.hours_count}
  =' @sprint.edit_link  
  = @sprint.delete_link